"""
Voicebox local API client.

Wraps the REST surface exposed by the Voicebox desktop app at
http://127.0.0.1:17493.  Requires Voicebox to be running.

Docs auto-generated by FastAPI:  http://127.0.0.1:17493/docs
GitHub:  https://github.com/jamiepine/voicebox
"""

import os
import pathlib
import tempfile
import time
from typing import Optional

import requests

VOICEBOX_BASE = os.getenv("VOICEBOX_URL", "http://127.0.0.1:17493")
DEFAULT_CLIENT_ID = os.getenv("VOICEBOX_CLIENT_ID", "voicebox-agent-demo")
DEFAULT_TIMEOUT = 60


class VoiceboxError(RuntimeError):
    """Raised when the Voicebox API returns a non-2xx response."""


class VoiceboxClient:
    """Thin, synchronous wrapper around the Voicebox localhost REST API."""

    def __init__(
        self,
        base_url: str = VOICEBOX_BASE,
        client_id: str = DEFAULT_CLIENT_ID,
        timeout: int = DEFAULT_TIMEOUT,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.last_generation_info: dict = {}
        self._session = requests.Session()
        self._session.headers.update({"X-Voicebox-Client-Id": client_id})

    # ------------------------------------------------------------------
    # Health
    # ------------------------------------------------------------------

    def is_running(self) -> bool:
        """Return True if the Voicebox API is reachable."""
        try:
            r = self._session.get(f"{self.base_url}/health", timeout=3)
            return r.ok
        except requests.ConnectionError:
            return False

    def health(self) -> dict:
        """
        Return the health payload, e.g.::

            {
              "status": "healthy",
              "gpu_available": true,
              "gpu_type": "MPS (Apple Silicon)",
              "backend_type": "mlx",
              ...
            }
        """
        return self._get("/health")

    # ------------------------------------------------------------------
    # Discovery
    # ------------------------------------------------------------------

    def list_models(self) -> list[dict]:
        """
        Return the full model catalogue with download / load status.
        Each entry has ``model_name``, ``display_name``, ``downloaded``,
        ``loaded``, and ``size_mb``.
        """
        return self._get("/models/status").get("models", [])

    def list_profiles(self) -> list[dict]:
        """Return all voice profiles (cloned voices + presets)."""
        return self._get("/profiles")

    # ------------------------------------------------------------------
    # Speech synthesis
    # ------------------------------------------------------------------

    def speak(
        self,
        text: str,
        profile: Optional[str] = None,
        personality: bool = False,
        poll_interval: float = 0.5,
        poll_timeout: float = 60.0,
    ) -> bytes:
        """
        Speak *text* and return raw WAV bytes.

        /speak is asynchronous — this method queues the job, polls
        GET /history/{id} until status is 'completed', then fetches
        the audio from GET /audio/{id}.

        Args:
            text:         Text to synthesise.
            profile:      Profile name (case-insensitive) or id.
            personality:  Rewrite through the profile's personality LLM first.
            poll_interval: Seconds between status polls (default 0.5).
            poll_timeout:  Max seconds to wait for generation (default 60).
        """
        payload: dict = {"text": text, "personality": personality}
        if profile:
            payload["profile"] = profile

        try:
            r = self._session.post(
                f"{self.base_url}/speak", json=payload, timeout=self.timeout
            )
        except requests.ConnectionError as exc:
            raise VoiceboxError(
                f"Voicebox disconnected on POST /speak: {exc}"
            ) from exc
        self._raise_for_status(r)
        gen_id = r.json()["id"]
        return self._wait_and_fetch(gen_id, poll_interval, poll_timeout)

    def generate(
        self,
        text: str,
        profile_id: str,
        language: str = "en",
        poll_interval: float = 0.5,
        poll_timeout: float = 60.0,
    ) -> bytes:
        """
        Full generation endpoint with explicit profile_id and language.
        Returns raw WAV bytes (waits for async completion).
        """
        payload = {"text": text, "profile_id": profile_id, "language": language}
        r = self._session.post(
            f"{self.base_url}/generate", json=payload, timeout=self.timeout
        )
        self._raise_for_status(r)
        gen_id = r.json()["id"]
        return self._wait_and_fetch(gen_id, poll_interval, poll_timeout)

    def create_preset_profile(
        self,
        name: str,
        preset_engine: str,
        preset_voice_id: str,
        language: str = "en",
    ) -> dict:
        """
        Create a preset voice profile (no audio sample required).

        Example engines / voice IDs:
            kokoro / am_michael, am_echo, bf_emma, af_sarah …
        """
        payload = {
            "name": name,
            "voice_type": "preset",
            "preset_engine": preset_engine,
            "preset_voice_id": preset_voice_id,
            "language": language,
        }
        r = self._session.post(
            f"{self.base_url}/profiles", json=payload, timeout=self.timeout
        )
        self._raise_for_status(r)
        return r.json()

    def list_preset_voices(self, engine: str = "kokoro") -> list[dict]:
        """Return the built-in preset voices for *engine*."""
        data = self._get(f"/profiles/presets/{engine}")
        if isinstance(data, dict):
            return data.get("voices", [])
        return data

    # ------------------------------------------------------------------
    # Speech-to-text
    # ------------------------------------------------------------------

    def transcribe(
        self,
        audio_path: str | pathlib.Path,
        model: str = "whisper-turbo",
    ) -> str:
        """
        Transcribe a local audio file (WAV/MP3/M4A/…) via Whisper.

        Returns the cleaned transcript string.
        """
        audio_path = pathlib.Path(audio_path)
        if not audio_path.exists():
            raise FileNotFoundError(audio_path)

        with audio_path.open("rb") as f:
            r = self._session.post(
                f"{self.base_url}/transcribe",
                files={"audio": (audio_path.name, f)},
                data={"model": model},
                timeout=self.timeout,
            )
        self._raise_for_status(r)
        return r.json().get("text", "")

    # ------------------------------------------------------------------
    # Voice cloning
    # ------------------------------------------------------------------

    def clone_voice(
        self,
        audio_path: str | pathlib.Path,
        name: str,
    ) -> str:
        """
        Create a new voice profile from a reference audio clip
        (10–30 s of clean speech).

        Returns the new profile's id.
        """
        audio_path = pathlib.Path(audio_path)
        if not audio_path.exists():
            raise FileNotFoundError(audio_path)

        with audio_path.open("rb") as f:
            r = self._session.post(
                f"{self.base_url}/profiles",
                files={"audio": (audio_path.name, f)},
                data={"name": name},
                timeout=self.timeout,
            )
        self._raise_for_status(r)
        return r.json().get("id", "")

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    def speak_and_save(
        self,
        text: str,
        output_path: str | pathlib.Path,
        profile: Optional[str] = None,
    ) -> pathlib.Path:
        """Synthesise *text* and write the WAV to *output_path*."""
        wav = self.speak(text, profile=profile)
        out = pathlib.Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(wav)
        return out

    def speak_to_temp(
        self,
        text: str,
        profile: Optional[str] = None,
    ) -> pathlib.Path:
        """Synthesise *text* into a temporary WAV file and return its path."""
        wav = self.speak(text, profile=profile)
        fd, path = tempfile.mkstemp(suffix=".wav", prefix="vb_")
        os.write(fd, wav)
        os.close(fd)
        return pathlib.Path(path)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def unload_model(self, model_name: str) -> None:
        """
        Unload *model_name* from GPU memory without deleting it.
        Voicebox will fall back to the next available model of the same engine.

        Example::

            client.unload_model("qwen-tts-1.7B")  # frees VRAM; 0.6B takes over
        """
        r = self._session.post(
            f"{self.base_url}/models/{model_name}/unload", timeout=self.timeout
        )
        # 404 just means it wasn't loaded — not an error worth raising.
        if not r.ok and r.status_code != 404:
            self._raise_for_status(r)

    def _wait_and_fetch(
        self,
        gen_id: str,
        poll_interval: float = 0.5,
        poll_timeout: float = 60.0,
    ) -> bytes:
        """Poll /history/{gen_id} until complete, then GET /audio/{gen_id}."""
        deadline = time.monotonic() + poll_timeout
        while time.monotonic() < deadline:
            try:
                r = self._session.get(
                    f"{self.base_url}/history/{gen_id}", timeout=self.timeout
                )
            except requests.ConnectionError as exc:
                raise VoiceboxError(
                    f"Voicebox disconnected while waiting for generation {gen_id}: {exc}"
                ) from exc
            self._raise_for_status(r)
            data = r.json()
            status = data.get("status")
            if status == "completed":
                self.last_generation_info = data
                try:
                    audio_r = self._session.get(
                        f"{self.base_url}/audio/{gen_id}", timeout=self.timeout
                    )
                except requests.ConnectionError as exc:
                    raise VoiceboxError(
                        f"Voicebox disconnected while fetching audio {gen_id}: {exc}"
                    ) from exc
                self._raise_for_status(audio_r)
                return audio_r.content
            if status == "failed":
                raise VoiceboxError(
                    f"Generation {gen_id} failed: {data.get('error')}"
                )
            time.sleep(poll_interval)
        raise VoiceboxError(
            f"Generation {gen_id} did not complete within {poll_timeout}s"
        )

    def _get(self, path: str) -> list | dict:
        r = self._session.get(f"{self.base_url}{path}", timeout=self.timeout)
        self._raise_for_status(r)
        return r.json()

    def _post_bytes(self, path: str, **kwargs) -> bytes:
        r = self._session.post(
            f"{self.base_url}{path}", timeout=self.timeout, **kwargs
        )
        self._raise_for_status(r)
        return r.content

    @staticmethod
    def _raise_for_status(response: requests.Response) -> None:
        if not response.ok:
            try:
                detail = response.json().get("detail", response.text)
            except Exception:
                detail = response.text
            raise VoiceboxError(
                f"Voicebox API {response.status_code}: {detail}"
            )
