import { ShoppingCart } from "@mui/icons-material";
import {
  Alert,
  Box,
  Button,
  Container,
  Paper,
  TextField,
  Typography,
} from "@mui/material";
import { useState } from "react";
import { marketplaceApi } from "../../api/marketplace";
import type { Order } from "./types";

export default function MarketplacePage() {
  const [userId, setUserId] = useState("user_1");
  const [amount, setAmount] = useState(1999);
  const [result, setResult] = useState<Order | null>(null);
  const [error, setError] = useState<string>("");
  const [loading, setLoading] = useState(false);

  const handleCreateOrder = async () => {
    setError("");
    setResult(null);
    setLoading(true);

    try {
      const response = await marketplaceApi.createOrder({
        user_id: userId,
        amount_cents: amount,
      });
      setResult(response);
    } catch (err: any) {
      setError(
        err.response?.data?.detail || err.message || "Failed to create order"
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Box sx={{ mb: 4 }}>
        <Typography
          variant="h4"
          gutterBottom
          sx={{ display: "flex", alignItems: "center", gap: 1 }}
        >
          <ShoppingCart />
          Marketplace Demo
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Contract-first design with FastAPI + React + Kafka (Confluent)
        </Typography>
      </Box>

      <Paper elevation={3} sx={{ p: 4 }}>
        <Box sx={{ display: "flex", flexDirection: "column", gap: 3 }}>
          <TextField
            label="User ID"
            value={userId}
            onChange={(e) => setUserId(e.target.value)}
            fullWidth
            helperText="Unique user identifier"
          />

          <TextField
            label="Amount (cents)"
            type="number"
            value={amount}
            onChange={(e) => setAmount(Number(e.target.value))}
            fullWidth
            helperText={`$${(amount / 100).toFixed(2)}`}
          />

          <Button
            variant="contained"
            size="large"
            onClick={handleCreateOrder}
            disabled={loading || !userId || amount <= 0}
            startIcon={<ShoppingCart />}
          >
            {loading ? "Creating..." : "Create Order"}
          </Button>

          {error && (
            <Alert severity="error" onClose={() => setError("")}>
              {error}
            </Alert>
          )}

          {result && (
            <Alert severity="success">
              <Typography variant="subtitle2" gutterBottom>
                Order Created Successfully!
              </Typography>
              <Box
                component="pre"
                sx={{ mt: 1, fontSize: "0.875rem", whiteSpace: "pre-wrap" }}
              >
                {JSON.stringify(result, null, 2)}
              </Box>
            </Alert>
          )}
        </Box>
      </Paper>

      <Box sx={{ mt: 4 }}>
        <Typography variant="h6" gutterBottom>
          Architecture Highlights
        </Typography>
        <Paper sx={{ p: 2, bgcolor: "grey.50" }}>
          <Typography
            variant="body2"
            component="div"
            sx={{ "& ul": { pl: 2 } }}
          >
            <ul>
              <li>
                <strong>OpenAPI</strong>: HTTP contract auto-generated by
                FastAPI at <code>/docs</code>
              </li>
              <li>
                <strong>AsyncAPI</strong>: Event contract spec for Kafka
                messages
              </li>
              <li>
                <strong>Routing</strong>: Events routed via Kafka topic{" "}
                <code>orders.created</code>
              </li>
              <li>
                <strong>Consumer Groups</strong>: Payment service scales with{" "}
                <code>payment-service-v1</code> group
              </li>
              <li>
                <strong>Data Contract</strong>: Orders owned by API service,
                Payments owned by consumer service
              </li>
            </ul>
          </Typography>
        </Paper>
      </Box>
    </Container>
  );
}
