"""
Proof document generator.

Produces a timestamped markdown file that captures the full agent trace —
what each agent reasoned, what code was produced at each step, and the
final test results. This is the artifact that proves the system worked.
"""
import time
from datetime import datetime
from pathlib import Path

from system import CodingState

AGENT_EMOJI = {
    "PLANNER": "🗺️",
    "CODER": "💻",
    "EVALUATOR": "🧪",
    "DEBUGGER": "🔧",
}


def generate_proof(state: CodingState, model_name: str, output_dir: Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    proof_path = output_dir / f"proof_{ts}.md"

    total = time.time() - state["t_start"]
    passed = state["passed"]
    iterations = state["iteration"]
    verdict = "✅ PASSED" if passed else "❌ FAILED"

    # Count agent calls by type
    agent_counts: dict[str, int] = {}
    for log in state["logs"]:
        agent_counts[log["agent"]] = agent_counts.get(log["agent"], 0) + 1

    lines: list[str] = [
        "# 🤖 Multi-Agent Coding — Proof of Execution",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| **Generated** | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |",
        f"| **Model** | `{model_name}` (local, Ollama — zero API cost) |",
        f"| **Result** | {verdict} |",
        f"| **Debug iterations** | {iterations} |",
        f"| **Total duration** | {total:.1f}s |",
        f"| **Agent calls** | {', '.join(f'{k}: {v}' for k, v in agent_counts.items())} |",
        "",
        "---",
        "",
        "## Task",
        "",
        f"> {state['task'].strip()}",
        "",
        "---",
        "",
        "## Agent Trace",
        "",
    ]

    t_ref = state["t_start"]
    for log in state["logs"]:
        agent = log["agent"]
        emoji = AGENT_EMOJI.get(agent, "🤖")
        t0 = log["t_start"] - t_ref
        t1 = log["t_end"] - t_ref
        dur = log["t_end"] - log["t_start"]

        lines += [
            f"### {emoji} {agent}  `+{t0:.1f}s → +{t1:.1f}s`  ({dur:.1f}s)",
            "",
        ]

        summary = log["summary"]
        # If the CODER/DEBUGGER summary is just metadata, no need to indent it specially
        if agent in ("PLANNER",):
            lines += [
                "<details>",
                f"<summary>Full plan</summary>",
                "",
                summary,
                "",
                "</details>",
                "",
            ]
        else:
            lines += [summary, ""]

    # Show code evolution if there were debug iterations
    lines += [
        "---",
        "",
        "## Final Solution (`solution.py`)",
        "",
        "```python",
        state["code"] or "# No code was generated",
        "```",
        "",
        "---",
        "",
        "## Test Results",
        "",
        "```",
        state["test_output"] or "(no tests were run)",
        "```",
        "",
        "---",
        "",
        "## Verdict",
        "",
        f"**{verdict}**",
        "",
        f"- Model: `{model_name}` — local inference, no cloud API",
        f"- Time: {total:.1f}s",
        f"- Debug cycles: {iterations}/{_max_iter()}",
        f"- Workspace: `{state['workspace']}`",
        "",
        "_Generated by multi-agent-coding — 4-agent LangGraph pipeline_",
    ]

    proof_path.write_text("\n".join(lines))
    return proof_path


def _max_iter() -> int:
    from system import MAX_ITERATIONS
    return MAX_ITERATIONS
